source 'https://rubygems.org'
ruby '2.3.3'

gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.0.6'
gem 'redis'
gem 'sidekiq'
gem 'sidekiq-failures', '~> 1.0'
gem 'acts_as_list'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'

group :development, :test do
  gem 'letter_opener'

  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'rspec-rails', '~>3.6'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
